Matt/master/random element
jankapunkt/js-set-extension pull request #30
Opened 2019-04-13 20:53 UTC by MareoRaft

PR for #27 

`randomElement` method created.  Usage: `A.randomElement()`.

I was not able to test that the element chosen is truly chosen "at random", nor could i test that the randomness is uniform.  I think some special testing tools would be necessary for this.  That being said, I don't think it's something to worry about.  I'm confident that the function does indeed work correctly.  You can verify yourself that the formula used here matches the formula given in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random#Getting_a_random_integer_between_two_values_inclusive, which guarantees a random choice with a uniform distribution.

2019-04-16 18:05 UTC, jankapunkt requested changes
Implentation is fine. Can be merged once the typo is fixed.

2019-04-16 18:05 UTC, jankapunkt commented on package/lib/index.js
> + * @returns {*} An element chosen randomly from the current set that could by of any type, depending on the elements of the set.
Typo in " could by of any type"

2019-04-20 21:15 UTC, MareoRaft commented on package/lib/index.js
> + * @returns {*} An element chosen randomly from the current set that could by of any type, depending on the elements of the set.
typo now fixed

2019-04-20 21:16 UTC, MareoRaft commented
merge conflicts fixed.  ok to merge once Travis succeeds.

2019-05-01 18:42 UTC, jankapunkt approved these changes

2019-05-01 18:43 UTC, merged